export type ChipData = {
  id: number;
  label: string;
};

export const cities: ChipData[] = [
  { id: 1, label: "Los Angeles" },
  { id: 2, label: "Long Beach" },
  { id: 3, label: "Santa Clarita" },
  { id: 4, label: "Glendale" },
  { id: 5, label: "Lancaster" },
  { id: 6, label: "Palmdale" },
  { id: 7, label: "Pomona" },
  { id: 8, label: "Torrance" },
  { id: 9, label: "Pasadena" },
  { id: 10, label: "East Los Angeles CDP" },
  { id: 11, label: "Downey" },
  { id: 12, label: "West Covina" },
  { id: 13, label: "El Monte" },
  { id: 14, label: "Inglewood" },
  { id: 15, label: "Burbank" },
  { id: 16, label: "Norwalk" },
  { id: 17, label: "Compton" },
  { id: 18, label: "Carson" },
  { id: 19, label: "Santa Monica" },
  { id: 20, label: "South Gate" },
  { id: 21, label: "Hawthorne" },
  { id: 22, label: "Whittier" },
  { id: 23, label: "Alhambra" },
  { id: 24, label: "Lakewood" },
  { id: 25, label: "Bellflower" },
  { id: 26, label: "Baldwin Park" },
  { id: 27, label: "Redondo Beach" },
  { id: 28, label: "Lynwood" },
  { id: 29, label: "Montebello" },
  { id: 30, label: "Pico Rivera" },
  { id: 31, label: "Florence-Graham CDP" },
  { id: 32, label: "Monterey Park" },
  { id: 33, label: "Gardena" },
  { id: 34, label: "Arcadia" },
  { id: 35, label: "South Whittier CDP" },
  { id: 36, label: "Diamond Bar" },
  { id: 37, label: "Huntington Park" },
  { id: 38, label: "Hacienda Heights CDP" },
  { id: 39, label: "Paramount" },
  { id: 40, label: "Glendora" },
  { id: 41, label: "Covina" },
  { id: 42, label: "Rosemead" },
  { id: 43, label: "Azusa" },
  { id: 44, label: "Cerritos" },
  { id: 45, label: "Rowland Heights CDP" },
  { id: 46, label: "La Mirada" },
  { id: 47, label: "Altadena CDP" },
  { id: 48, label: "Rancho Palos Verdes" },
  { id: 49, label: "Culver City" },
  { id: 50, label: "San Gabriel" },
  { id: 51, label: "Bell Gardens" },
  { id: 52, label: "La Puente" },
  { id: 53, label: "Monrovia" },
  { id: 54, label: "Claremont" },
  { id: 55, label: "Temple City" },
  { id: 56, label: "West Hollywood" },
  { id: 57, label: "Manhattan Beach" },
  { id: 58, label: "San Dimas" },
  { id: 59, label: "Bell" },
  { id: 60, label: "Beverly Hills" },
  { id: 61, label: "Lawndale" },
  { id: 62, label: "La Verne" },
  { id: 63, label: "Walnut" },
  { id: 64, label: "South Pasadena" },
  { id: 65, label: "Maywood" },
  { id: 66, label: "San Fernando" },
  { id: 67, label: "Calabasas" },
  { id: 68, label: "Cudahy" },
  { id: 69, label: "Duarte" },
  { id: 70, label: "Lomita" },
  { id: 71, label: "La Cañada Flintridge" },
  { id: 72, label: "Agoura Hills" },
  { id: 73, label: "Hermosa Beach" },
  { id: 74, label: "South El Monte" },
  { id: 75, label: "Santa Fe Springs" },
  { id: 76, label: "El Segundo" },
  { id: 77, label: "Artesia" },
  { id: 78, label: "Hawaiian Gardens" },
  { id: 79, label: "Palos Verdes Estates" },
  { id: 80, label: "San Marino" },
  { id: 81, label: "Commerce" },
  { id: 82, label: "Signal Hill" },
  { id: 83, label: "Sierra Madre" },
  { id: 84, label: "Malibu" },
  { id: 85, label: "Rolling Hills Estates" },
  { id: 86, label: "Westlake Village" },
  { id: 87, label: "La Habra Heights" },
  { id: 88, label: "Avalon" },
  { id: 89, label: "Rolling Hills" },
  { id: 90, label: "Hidden Hills" },
  { id: 91, label: "Irwindale" },
  { id: 92, label: "Bradbury" },
  { id: 93, label: "Industry" },
  { id: 94, label: "Vernon" },
];